<?php

 return  array("Tabasco" => "develop.tab@aiesec.org.mx" ,
"Aguascalientes" => "develop.ags@aiesec.org.mx" ,
"Chihuahua" => "develop.chih@aiesec.org.mx" ,
"Chiapas" => "jorge.sanchez@aiesec.net" ,
"Cdad Juárez" => "develop.cj@aiesec.org.mx" ,
"Guadalajara" => "develop.gdl@aiesec.org.mx" ,
"Guanajuato" => "develop.gto@aiesec.org.mx" ,
"Hermosillo" => "develop.hmoo@aiesec.org.mx" ,
"IPN" => "develop.ipn@aiesec.org.mx" ,
"ITAM" => "develop.it@aiesec.org.mx" ,
"Nayarit" => "saul.perezcartro@aiesec.net" ,
"ITESM CEM" => "develop.em@aiesec.org.mx" ,
"ITESM MTY" => "develop.mty@aiesec.org.mx" ,
"ITESM Santa Fe" => "develop.sf@aiesec.org.mx" ,
"ITESM Toluca" => "develop.itesmtoluca@aiesec.org.mx" ,
"La Laguna" => "develop.laguna@aiesec.org.mx" ,
"León" => "develop.leon@aiesec.org.mx" ,
"Mérida" => "develop.mer@aiesec.org.mx" ,
"Oaxaca" => "develop.oax@aiesec.org.mx" ,
"Puebla" => "develop.pue@aiesec.org.mx" ,
"Querétaro" => "develop.qro@aiesec.org.mx" ,
"Sinaloa" => "develop.sin@aiesec.org.mx" ,
"Los Mochis" => "develop.sin@aiesec.org.mx" ,
"UAEMEX" => "develop.uaemex@aiesec.org.mx" ,
"UNAM" => "develop.unam@aiesec.org.mx" ,
"UP" => "develop.up@aiesec.org.mx" ,
"Veracruz" => "develop.ver@aiesec.org.mx" ,
"Zacatecas" => "develop.zac@aiesec.org.mx" ,
"Irapuato" => "isabel.sanchez8@aiesec.net" ,
"Tijuana" => "develop.@aiesec.org.mx" ,
"Hidalgo" => "develop.@aiesec.org.mx" ,
"ITESM CCM" => "develop.em@aiesec.org.mx" ,
"Michoacan" => "juanpablo.barrigadiaz@aiesec.net" ,
"Celaya" => "develop.celaya@aiesec.org.mx "
);
?>